apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer 
  ports:
    - port: 8081
      targetPort: 8081
    
---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service-repo
  namespace: tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8085'
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer 
  ports:
    - port: 8085
      targetPort: 8085
    


