apiVersion: v1  
kind: Service
metadata:
  name: node-app
  namespace: dev
spec:
  selector: 
    app: node-app
  # type: NodePort
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1  
kind: Service
metadata:
  name: node-app
  namespace: dev
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer 
  ports:
    - port: 8085
      targetPort: 8085